/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menubar from "@/components/Menubar";
import { FaAngleDown, FaQuestionCircle } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <Menubar />
        <div className="flex-col w-full">
          <div className={inter.className}>
            <header className="p-6 border-t border-b flex justify-end">
              <div className="flex items-center gap-14">
                {/* Help icon */}
                <div className="relative">
                  <FaQuestionCircle size={24}/>
                </div>
                
                {/* about user */}
                <div className="flex gap-4">
                  <img src="https://ui-avatars.com/api/?background=c7d2fe&color=3730a3&bold=true" alt="" className="w-10 h-10 rounded-full" />
                  <div className={'flex gap-5 justify-between items-center overflow-hidden transition-all'}>
                    <div className="leading-4 dark:text-white">
                      <h4 className="font-semibold">John Doe</h4>
                      <span className="text-xs text-gray-600">Admin</span>
                    </div>
                    <FaAngleDown />
                  </div>
                </div>
              </div>
            </header>
            {children}
            {/* Here you can Import or Create Common Footer */}
          </div>
        </div>
      </body>
    </html>
  );
}
